### ISSUE TITLE
ES-check error

### ISSUE THREAD

**Issue by joetidee** [mysticatea/abort-controller#18]
Am getting this error with v3.0.0:
```
ES-Check: there were 1 ES version matching errors.

          ES-Check Error:
          ----
          · erroring file: ./dist/static/vendor.4cd45c7aadabd101b1e0.js
          · error: SyntaxError: The keyword 'const' is reserved (30:92360)
          · see the printed err.stack below for context
          ----

```

The application used is universal, so will be run in the browser and in node - how to fix this?

**Comment by mysticatea** [comment]
Both browsers and node support `const` declarations.

I'm not sure what ES-Check is, but I think that it's ES-Check's problem.

**Comment by joetidee** [comment]
So, `es-check` will check whether files used in our project are suitably transpiled - in our case to `es2015`. There is a `const` in `abort-controller.js` which suggests that it hasn't been transpiled to `es2015`. Are you able to supply a distribution file that has been transpiled to `es2015`?

**Comment by mysticatea** [comment]
I don't have any plan to transpile this module. Please transpile this if you need.

Because transpile is not zero cost. For example, it needs some glue code to reproduce classes for ES5. If each library has own glue code, those are redundant and increasing bundle size. On the other hand, app side transpiling can aggregate all glue code.
